### ISSUE TITLE
Suggested improvement

### ISSUE THREAD

**Issue by martianovdev** [chokobole/data_view#1]
While exploring your beautiful library, I noticed a minor inaccuracy in the code that may affect the outcome of compilation.
I propose a fix for the WriteBigEndian method, replacing the variable "out" with "buf"

`
template <typename T>
inline void WriteBigEndian(char* buf, T val) {
  memcpy(out, static_cast<const T*>(&val), sizeof(T));
}
`

Corrected version:
`
template <typename T>
inline void WriteBigEndian(char* buf, T val) {
  memcpy(buf, static_cast<const T*>(&val), sizeof(T));
}
`

**Comment by chokobole** [comment]
@MikhailMartianov Yes you're right! Thanks to let me know this! It was built a very long time ago and hasn't been maintained long..!
